### ISSUE TITLE
Instant response in Socket.js should be an option

### ISSUE THREAD

**Issue by jloveric** [howdyai/botkit#1075]
I have a bot that performs a lot of computation behind the scenes so there is a delay because of all the computation.  Socket.js puts an additional delay to mimic typing, in my case this makes many of the operations noticeably slow.  Turning off the response delay should be an option.

**Comment by peterswimm** [comment]
related: https://github.com/howdyai/botkit-starter-web/issues/13#issuecomment-334346378

**Comment by jloveric** [comment]
Another possibly solution is to put in a "startTyping" call which starts the bot typing and then you call send when your response is finally constructed.  This would tell the user that something is actually happening because you could see the bubble starting.  Anyway, more complicated ...  So simply turning off the delay should still be an option.

**Comment by benbrown** [comment]
This is done!

I have changed the behavior of this feature.

By default, there will be no delay.
You can turn on delay in a variety of ways:

* add replyWithTyping: true to your controller config
* use bot.replyWithTyping to send your reply instead of bot.reply
* set message.typingDelay to delay in ms
