### ISSUE TITLE
Bot responding to itself

### ISSUE THREAD

**Issue by caske33** [howdyai/botkit#110]
If I have a bot responding in public to a slash command, the bot itself can react to that message if it contains a keyword. 

(I haven't tried this, but I'm guessing you can create an infinite chain this way if the bot responds with "hi" on the keyword "hi").

In any case, I think this behaviour is in most cases not what is wanted.

**Comment by dossy** [comment]
Thanks to code like https://github.com/howdyai/botkit/blob/master/lib/SlackBot.js#L476-L478, the default `message_received` handler will not trigger on messages originated by the bot itself:

```
                    if (message.user == bot.identity.id) {
                        return false;
                    }
```

If you register your own `message_received` handler, then yes, in it you will need to take care to handle messages originated by the bot correctly, to avoid infinitely repeating cycles.  But, for the typical user of Botkit, it's already taken care of.

+invalid

**Comment by caske33** [comment]
I was just using the controller.hears handler and still got the issue of the bot replying to itself.

**Comment by dossy** [comment]
@caske33 What version of Botkit are you using?

```
> require('botkit/package.json').version
'0.0.12'
```

**Comment by caske33** [comment]
That was in 0.0.5

**Comment by dossy** [comment]
@caske33 strange -- the code that detects messages from the bot itself has been in there ever since the first commit back on 2015-12-14.

Oh, wait - I re-read your original issue more carefully - I'm not 100% sure because I haven't tested this, but I'm guessing that the response to the slash command is not of `message.type == 'message'` so yes, the default `message_received` handler simply delegates that event with a `slack_botkit.trigger(message.type, [bot, message])` which you can then act on.

The code I was referring to prevents the bot from reacting to its own messages (i.e., `message.type == 'message'`), but slash command responses are their own message type (i.e., `message.type == 'slash_command'`).

So, the bot could reply to its own `slash_command` message, but shouldn't respond to its own `message` messages.

**Comment by peterswimm** [comment]
@caske33 Did you ever manage to fix this issue?

**Comment by peterswimm** [comment]
I am closing this issue for now, if there is any additional issue to add, please go ahead and reply, and I will reopen.

**Comment by maxrobertcohen** [comment]
how can i get the bot _to_ respond to its own messages? I want to have a series of button options, and the resulting text from each button selection triggers the next round of buttons

**Comment by asopinka** [comment]
@maxrobertcohen you should be doing that using [interactive messages](https://botkit.ai/docs/readme-slack.html#interactive-messages) and then botkit will send it to 

```javascript
controller.on('interactive_message_callback', function(bot, message) {
    // message.original_message is the original message
    // message.callback_id is the callback id you specified
    // message.actions contains the button/other item that the user interacted with
});
```

**Comment by maxrobertcohen** [comment]
trying to implement but im fairly new to this so am having trouble getting it working.  not sure how to use the message.actions and message.original_message to look for the first button's activation to trigger the new one 

hacking away, learning as i go
