### ISSUE TITLE
[Facebook] Platform v2.2: Page Insights API

### ISSUE THREAD

**Issue by jonchurch** [howdyai/botkit#1126]
With Facebook Messenger Platform v2.2 Page Insights API was introduced [(docs)](https://developers.facebook.com/docs/messenger-platform/reference/messaging-insights-api/)

This is an API feature which should be added similarly to how the other FB api's are implemented in [Facebook.js](https://github.com/howdyai/botkit/blob/66464ae92849873e9ca0272c97b89beb7bb5588d/lib/Facebook.js#L823)

Anyone interested? Good first contribution for somebody 👍 

Let me know if I can help you!

**Comment by kniteshift** [comment]
I am a bit interested on implementing this but I guess it would depend on not so much the how we capture, but what do we do with it and where do we store it. 

It also seems like the documentation you linked seems to be meant for querying the data from the Insights API to view the analytics on the messaging, rather than adding data points to the API.

**Comment by ouadie-lahdioui** [comment]
@kniteshift you will work on it ?

**Comment by ouadie-lahdioui** [comment]
@jonchurch are you already on it ?
