### ISSUE TITLE
[Web] Connection Events

### ISSUE THREAD

**Issue by hwhelchel** [howdyai/botkit#1248]
If a user refreshes their browser, Botkit sends a `welcome_back` message from the client. The server then translates this into a `reconnect` event.

https://github.com/howdyai/botkit/blob/master/lib/Web.js#L79-L81

If the disconnect here is voluntary, because the user refreshed the page, should `welcome_back` be allowed to pass through?

I think the UX here would be better. The user would not anticipate that they would keep their place in their chat when refreshing the browser.

Is there a way to distinguish between voluntary disconnects vs. involuntary disconnects due to network connectivity issues? 

@benbrown or @peterswimm if either of you all can point me in the right direction, happy to submit the PR.

**Comment by benbrown** [comment]
hey @hwhelchel good point.

I think this should fire a DIFFERENT event - one that indicates a "natural" disconnect/reconnect, rather than one caused by interference or networking problems.

There is not CURRENTLY a way to do this, but since the welcome_back event is triggered based on the presence or absence of a cookie, it would be possible to add some logic around that...

One solution I had considered is only firing the `welome_back` event after a specified period of time has elapsed since first connection.  For example, greater than 30 minutes.

**Comment by hwhelchel** [comment]
Thanks for chiming in Ben. I'll see if I can circle back to this later this week and put some of your ideas into practice.
