### ISSUE TITLE
Facebook payment button error

### ISSUE THREAD

**Issue by jhaala** [howdyai/botkit#1363]
I'm having an issue getting payment buttons to work in Facebook. My code looks correct, payments are enabled on my page, and am testing with a user profile in the US with payments enabled. Any time I add a payment button to a working template I get this error: 

> ERROR in user profile API call:  Unsupported get request. Object with ID '1977168165650832' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

I'm assuming the referenced Object Id is the user's profile? This is not the same id I get from the profile object inside bot.getMessageUser().

![payment-btn](https://user-images.githubusercontent.com/11741743/40699946-392af86a-63a5-11e8-803a-d39c3fb12170.png)

**Comment by ouadie-lahdioui** [comment]
Hi @jhaala  👋 

Can you confirme that when you remove the payment button from your template, everything works fine ? Because the error is while calling FB user profile API !

Yes, the object id must be the user profile id and equivalent to profile.id inside bot.getMessageUser() gotten.

To help you debug, try to this two scenarios : 
## > Case 1 :
- Remove the payment button
- Catch a simple fb event, like that :
````
controller.hears(['^hello'], 'message_received', (bot, message) => {
    controller.api.user_profile(message.user)
        .then((result) => {
            console.log(JSON.stringify(result))
        });
});
````
What's the result ?

## > Case 2 :
- Add the payment button
- Catch a simple fb event, like that :
````
controller.hears(['^hello'], 'message_received', (bot, message) => {
    controller.api.user_profile(message.user)
        .then((result) => {
            console.log(JSON.stringify(result))
        });
});
````
What's the result ?

**Comment by ouadie-lahdioui** [comment]
Cool 👍
