### ISSUE TITLE
[Socket Bot] Deploy on AWS

### ISSUE THREAD

**Issue by lucasvercelot** [howdyai/botkit#1409]
Hi guys !

I'm trying to deploy my Botkit socket bot (Botkit anywhere) on my AWS machine but when I run it and access it, the bot keeps saying 'Disconnected... reconnecting!' and then timeout in 'Offline! Reload to reconnect.'
I have a nginx conf that handles http/https and is configured to redirect on localhost:3000.

Do you have any idea why I can't have the bot working on AWS ? (It works perfectly when I run it locally)

Thanks a lot in advance !

**Comment by pgoldweic** [comment]
Yes, I’ve gone through this myself. In AWS you need to use an ‘Application Load Balancer’ instead of the default load balancer used by Elastic Beanstalk (this is all configurable via the console at least, but probably also CLI), add the required http/https listener to it, and, very importantly, you need to include a special ‘.ebextensions’ configuration file for nginx for enabling websockets. 
Mine is as follows:

container_commands:
  enable_websockets:
    command: |
      sed -i '/\s*proxy_set_header\s*Connection/c \
              proxy_set_header Upgrade $http_upgrade;\
              proxy_set_header Connection "upgrade";\
              ' /tmp/deployment/config/#etc#nginx#conf.d#00_elastic_beanstalk_proxy.conf

(the name of this file doesn't matter, you can use something like 'enable-websockets.config' for example)
Hope this helps!

**Comment by lucasvercelot** [comment]
Hi @pgoldweic !

Your answer led me to find a solution.

I solved my problem by adding those 3 lines in my nginx conf file : 
` proxy_http_version 1.1; `
`proxy_set_header Upgrade $http_upgrade;`
`proxy_set_header Connection “upgrade”;`

Thank you for your help ! :)
