### ISSUE TITLE
Detect second word in message

### ISSUE THREAD

**Issue by chris-houston** [howdyai/botkit#1419]
I am trying to have my slack bot read a message "Add @Chris" and I want it to reply with "Added @Chris". I got my regex working but for some reason it doesn't respond at all. It literally just gives a 👍 to my message?? I've tried using message.match to get the second word (@Chris) but I am struggling on understanding why. My regex seems fine at

```
    controller.hears('Add (\@[a-zA-Z0-9_]+))','direct_mention', function(bot, message) {
        bot.reply(message, "Added " + message.match[1]);
    });
```

I dont know if my reply message is wrong, but I also dont know why it keeps 👍 to my message instead of replying.

**Comment by alexframe** [comment]
It's likely because the message won't come through as `@chris`, it'll come similar to `<@UB10DBJ5T>` instead.

Check this as example where I say `my name is @alex` and it comes through as `my name is <@UB10DBj5T>`.

<img width="433" alt="screen shot 2018-07-20 at 2 17 16 pm" src="https://user-images.githubusercontent.com/8746552/42983040-c34a441a-8c27-11e8-8204-aacc633ce50f.png">
<img width="522" alt="screen shot 2018-07-20 at 2 17 35 pm" src="https://user-images.githubusercontent.com/8746552/42983041-c37aaa6a-8c27-11e8-924c-8b48448a173a.png">

So your regex has to be adjusted to handle that format.

**Comment by chrishoustondev** [comment]
@alexframe Ive seen the ID before, but I guess I should say that I am stuck with the fact that it literally does not reply to me, it just does a reaction of a 👍 to my message instead
