### ISSUE TITLE
# of users for BotKit free?

### ISSUE THREAD

**Issue by carsonkraft** [howdyai/botkit#1443]
Does anyone know the exact amount of users that can interact with the bot in the free version? Also, if it exceeds that number, what happens? Does the bot just stop working until you pay or does it reset monthly?

**Comment by peterswimm** [comment]
In the free version of Botkit, the limits are largely what your production environment can handle. For example our Howdy bot handles many thousands of bots concurrent per server instance.

There is no charge for the number of users served in apps you host.

**Comment by pgoldweic** [comment]
Not sure if this is what you had in mind when you asked the question @carsonkraft, but there certainly *is* a limitation in the number of bots (and not users) you can create if you are using the free version of Botkit Studio though. You need to double check the specifics info. on this, but I believe that you can't run more than 1 bot using this free version (this assumes that you are using Botkit's Studio; otherwise the limitation is not there).

**Comment by peterswimm** [comment]
@pgoldweic there is no "free" version of botkit studio at the moment. There is a trial that is capped at one user, with finite usage stats that once consumed requires a active subscription to keep working. 

The trial only allows one bot per team, that is true, but if a bot is being actively used, you should upgrade to a basic account.

**Comment by pgoldweic** [comment]
Yes, you are right. I shouldn't have called it a 'free' version but a trial version. Sorry for the mistake :-(
