### ISSUE TITLE
setupWebserver not working on Azure Website

### ISSUE THREAD

**Issue by MiroValchev** [howdyai/botkit#150]
slack_botkit.setupWebserver

process.env.PORT is not a number in an Azure Website, hence this check fails:
         if (isNaN(port)) {
             throw new Error('Specified port is not a valid number');
         }

Is there a way we can fix this?

**Comment by anonrig** [comment]
Yes, I will fix this today. The solution will parse the string to integer and then check. Is it okay with your end @MiroValchev ?

**Comment by MiroValchev** [comment]
@anonrig I believe it should work with Azure - i.e. IIS pipes like \\.\pipe\4abc5c7e-1f61-4cc3-8b6f-b2a88020d64c for port.

**Comment by elahmo** [comment]
I manually removed those checks in order to make the bot work on Azure websites,  @michaelrway is correct, the pipes are used on Azure for PORT value and resolve to port eventually, but `isNaN()` returns true for that check.

**Comment by droda59** [comment]
Hi @MiroValchev, how did you configure your bot on Azure? Was it using an Api App or a Web App? I'm trying to do it with an Api App, like [this](https://azure.microsoft.com/en-us/documentation/articles/app-service-api-nodejs-api-app/), but I can't get it to work.

**Comment by MiroValchev** [comment]
WebApp really. It's a simple node.js server after all. I also have a public folder in there so that I can show a few pages about how my bot works etc.

**Comment by bashirsouid-ms** [comment]
Was there any other configuration you did to get this to work. I have had a crack at it for a while and havent gotten it to run. It works fine locally but fails in Azure. The logs dont reveal much of interest (perhaps I am looking at the wrong ones?).

It seems like it had some issues with the NPM install phase so as a test I tried including the node_modules folder in the deployment package (temporarily) but that did resolve it. I then tried using OneDrive as the deployment source so that I could verify that the exact folder that works locally on my box is what the cloud service uses but alas no dice. I changed "application settings" in Azure to include an env variable for the token (and even tried hard coding it into the file temporarily as a test). My script is the typical "server.js" file and the package.json file has this:

  "scripts": {
    "start": "node server"
  },

Is there something else to configure in terms of ports or handlers etc.?

**Comment by MiroValchev** [comment]
Haven't updated my bot so not sure how the latest versions of the related packages behave.
Still, for me the following configuration worked in the past:
1. Continious deployment from git
2. Setting environment variables 
3. Azure Web App as noted above 
4. Remove this check from botkit
if (isNaN(port)) {
throw new Error('Specified port is not a valid number');
}

**Comment by elahmo** [comment]
That process still works with the latest version.

**Comment by peterswimm** [comment]
Clos

**Comment by graemechristie** [comment]
It looks like this check is still in the latest code:

Our bot is build by a CI process .. are we expected to remove code from the node module after build somehow when deploying to Azure:

The check:
`
if (isNaN(port)) {
throw new Error('Specified port is not a valid number');
}
`
Should not be in the botkit npm module. Why is this issue closed ?

**Comment by elahmo** [comment]
@graemechristie there is a new setting that allows NaN port numbers: slack_botkit.config.webserver.allowNonNumericPort

Set it to 'true' and it wont cause issues.

**Comment by graemechristie** [comment]
That sound great. Looking at the code though, I can't see how this would work for the SlackBot:

https://github.com/howdyai/botkit/blob/master/lib/SlackBot.js#L352

**Comment by graemechristie** [comment]
and ... 

![image](https://cloud.githubusercontent.com/assets/1361894/25787511/a1692da4-33d4-11e7-9f19-92f8e11a2871.png)

Is this feature in a branch somewhere ...

**Comment by anonrig** [comment]
We don't really need the `isNaN` check, since port number isn't always a number.

**Comment by benbrown** [comment]
I finally made this change in 0.6.1!
