### ISSUE TITLE
Vocal output on botkit: is it possible?

### ISSUE THREAD

**Issue by valeadami** [howdyai/botkit#1556]
Hi guys, I am testing the web based botkit example. I wonder if there's a chance to get a vocal output from the chat and how. It's ok how it works now but the bot I am developing should help many users, included those visually impaired.

**Comment by benbrown** [comment]
you could certainly run the output through a text to speech synthesizer, and then attach the results to the outbound message or otherwise use the audio.  There are [a lot of ways to do text to speech](https://www.google.com/search?q=text+to+speech+api&rlz=1C5CHFA_enUS814US814&oq=text+to+speech+api&aqs=chrome..69i57j0l5.2230j0j1&sourceid=chrome&ie=UTF-8)

**Comment by valeadami** [comment]
ok thanks for the suggestion, i'll have a look at it!

**Comment by benbrown** [comment]
Let us know if you find a solution that you particularly like!
