### ISSUE TITLE
Problem with bot.getMessageUser() with Facebook

### ISSUE THREAD

**Issue by ca42rico** [howdyai/botkit#1557]
Hi,
since some days I'm having problems fetching profile data of facebook users.

It's caused by calling **bot.getMessageUser**(message) (removing this call it works).
I have read that the solution could be to remove "gender" (and perhaps also "timezone" and all the additional information required, apart from name and surname I believe) from the user profile request, for some updates of the privacy policy of Facebook.

There would be a way to get just "first_name" and "last_name" of an user and not "timezone", "gender", "locale", ..
Thanks

### What was the result you received?
```
{
	message: '(# 100) Insufficient authorization to access the user profile.',
	type: "OAuthException",
	code: 100,
	error_subcode: 2018247,
	fbtrace_id: 'AyMstghZkkb'
}
```
### Context:

- Botkit version: 0.7.0 (and 0.6.16)
- Messaging Platform: Facebook
- Node version: 11.6.0 (and 8.11.3) 
- Os: GNU/Linux

**Comment by ouadie-lahdioui** [comment]
Hello @ca42rico,

Your app have been approved in app review or not  ?

Because according to FB, to access additional user profile fields, you must apply for each field in the messenger platform tab of the app console when you submit your app.

To ignore gender and timezone, yes you can get only some specific fields by using ````controller.api.user_profile(message.user, 'field1&field2', yourCallback)```` method not ````bot.getMessageUser(message) ````, that allows you put the fields you want and get exactly the same result as ````.getMessageUser(...)````.

Let me know if that helps!

**Comment by ca42rico** [comment]
Hi @ouadie-lahdioui,

yes, my app was been approved.
With `controller.api.user_profile(...)` I should solve it.

Thank you very much, 
Cheers
