### ISSUE TITLE
Port the Jabber connector to the new format used by Botkit #next

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1573]

**Comment by w1nk** [comment]
Hi all!  What happened to this issue?  Is xmpp support completely abandoned?

**Comment by benbrown** [comment]
No, not abandoned.  However, I don't have the expertise nor the access to Cisco's jabber system.  The team that built the original adapter will have to port it to the new version.

**Comment by w1nk** [comment]
Hi @benbrown!  Thanks for the super fast response.  I don't have the botkit expertise (yet) to port the old adapter, but you should be able to work with the adapter via access to any xmpp server (including things like ejabberd, openfire, etc) since afaik the node-xmpp module doesn't support any cisco specific xmpp features.  Is there any kind of upgrading guide as to how to port an adapter from the previous version of botkit?  

Thanks!

**Comment by peterswimm** [comment]
@qiongfangzhang fyi!

**Comment by peterswimm** [comment]
@qiongfangzhang fyi!
