### ISSUE TITLE
bot.startConversation method undefined when using WebAdapter.

### ISSUE THREAD

**Issue by ksabariraj** [howdyai/botkit#1635]
** DO NOT ERASE THESE INSTRUCTIONS WITHOUT READING THEM FIRST **

Please read this entire template before posting any issue to get faster response.

Open an issue on this repository with your topic or question, providing as much detail as possible. The more we know, the better we can help.

Before posting, search the repository to see if there's already an issue opened to avoid duplicates.

### Are you sure this is an issue with the Botkit core module?

For all other questions, requests or help, please feel free to join the discussion slack : https://community.botkit.ai

### What are you trying to achieve or the steps to reproduce?

Describe your issue here, include as much detail as necessary to reproduce the issue or implement a missing functionality.

````
const {Botkit} = require('botkit');
const { WebAdapter } = require('botbuilder-adapter-web');

Bot = new Botkit({
        adapter: adapter,
  })

Bot.hear('help', function (bot, message) {
    bot.startConversation(message, function (err, convo) {
        //code
    });
})


````

### What was the result you received?

bot.startConversation : undifiend

### What did you expect?

function

### Context:

- Botkit version: 4.0.1
- Messaging Platform: WebAdapter
- Node version: 8
- Os: MAc
- Any other relevant information:

**Comment by benbrown** [comment]
When using the new WebAdapter in Botkit v4, it is no longer necessary to call startConversation -- instead, call `await bot.beginDialog(DIALOG_ID, {options})` --- [see docs here](https://botkit.ai/docs/v4/reference/core.html#begindialog)

In past versions of Botkit, there was a `startconversation` method that was used to construct dialogs on the fly. This has been replaced with the new `BotkitConversation` system. [Docs here](https://botkit.ai/docs/v4/conversations.html).

To avoid confusion, I will also mention that _some adapters_ do include functions like startPrivateConversation and startConversationWithUser -- however, these functions are used to _change the location of the conversation_ rather than anything to do with actually using the dialog system.

**Comment by ksabariraj** [comment]
@benbrown: Thanks for your time and details.
