### ISSUE TITLE
botkit  & botkit CMS integration mongoDB (webAdapter)

### ISSUE THREAD

**Issue by milestone35** [howdyai/botkit#1732]
Hi Boys ,
  I need some help . I want to botkit and botkit cms integration mongoDB but I could not this.
I have old version message history.js 

### bot.js
```
const { MongoDbStorage } = require('botbuilder-storage-mongodb');

// Load process.env values from .env file
require('dotenv').config();

let storage = null;
if (process.env.MONGO_URI) {
    storage = mongoStorage = new MongoDbStorage({
        url : process.env.MONGO_URI,
    });
}
```

and

### message_history.js

if (controller.storage && controller.storage.history) {

   // expose history as an endpoint
   controller.webserver.post('/botkit/history', function(req, res) {
     if (req.body.user) {

some one give me help to 

- [ ] mongodb integration()
![Capture](https://user-images.githubusercontent.com/46100382/61689981-f0b5ea00-ad30-11e9-9669-6fa323cde445.PNG)

- [ ] enabled message history 

thanks a lot.

   

-     "botbuilder-adapter-web": "^1.0.3",
-     "botbuilder-storage-mongodb": "^0.9.5",
-     "botkit": "^4.0.1",
-     "botkit-cms": "0.0.4",
-     "botkit-plugin-cms": "^1.0.0",
-     "botkit-rasa": "^1.0.7",
-     "botkit-storage-mongo": "^1.0.7",
-     "botkit-studio-metrics": "0.0.5",
-     "chatito": "^2.3.3",
-     "dotenv": "^7.0.0"

**Comment by milestone35** [comment]
### this try code  :
`//const controller = new Botkit({storage: myStorageAdapter});
const { MongoDbStorage } = require('botbuilder-storage-mongodb');
let storage = mongoStorage = new MongoDbStorage({
        url : process.env.MONGO_URI,
});`

**Comment by benbrown** [comment]
The type of storage provided by `botbuilder-storage-mongodb` is not the same as was present in the old Botkit, nor is it the same as what is needed for the history.

You will need to implement your own mechanism for storing, retrieving, and displaying the message history.  This functionality is no longer supported as part of the latest version of Botkit because securing this information requires integration with your app.

**Comment by milestone35** [comment]
thank you for helps @benbrown ,

**Comment by etiennellipse** [comment]
@benbrown It would be very helpful to have a guideline of some sort, or any indication at all, as to how to implement history storage; where to hook up in the pipeline, what can be stored, etc. As someone new exploring botkit seriously, the documentation left me puzzled about that aspect especially since it changed radically from 0.7.
