### ISSUE TITLE
Remove the revokable proxy behavior inherited from Bot Framework

### ISSUE THREAD

**Issue by benbrown** [howdyai/botkit#1841]
Is your feature request related to a problem? Please describe.
The current behavior of turning the "turn context" into a revokable proxy that stops working is hard to deal with and difficult to explain. We should (optionally) remove it from the Botkit adapters.

Describe the solution you'd like
By deriving a new class from BotAdapter, then changing all Botkit adapters to derive from that.

When used with Botkit the proxy behavior should be disabled by default.
Otherwise it should be on by default (this is the expected behavior when used with Bot Framework)

**Comment by movi1224** [comment]
Can you please see my comment on #1856 , I met some issues on that :(

**Comment by benbrown** [comment]
I think you misunderstand what this ticket is about.

This would be a change to the code inside the Botkit adapters to use a different base class - not a change to your bot code.

**Comment by benbrown** [comment]
Not stale.

**Comment by benbrown** [comment]
not stale

**Comment by pgoldweic** [comment]
Hi @benbrown, could you comment on whether this issue is behind a problem I've been having with my (converted to botkit4) bot application? Specifically, I  noticed that after a couple of botkit 'send'  middlewares are run , and before the response is actually sent by the bot, I was getting the dreaded "TypeError: Cannot perform 'get' on a proxy that has been revoked" on using setInterval to let bot reply repeatedly", even though I was using the 'await' as instructed in the docs before every call to bot.reply (and I'm not using setInterval).  Something to note is that my middlewares are themselves async functions, so they may take a little bit of time to run (they log to a -database backed- message history, and also to a couple of external endpoints). So following advice by @Naktibalda  on issue 1856, I decided to insert a call to 'bot.changeContext(message.reference)' before the line that awaits the call to bot.reply.  This seems to have resolved the issue for now (thanks @Naktibalda!), but I'm a bit unsure as to why this is needed, and also why it works. If you could comment and hopefully provide some insights on this, it would be very helpful. thanks!
