### ISSUE TITLE
Messenger Platform 1.1: Ratings, Quick Replies, Account Linking, and More

### ISSUE THREAD

**Issue by ansarizafar** [howdyai/botkit#305]
Is there any plan to implement these new Facebook messenger features?
[Messenger Platform 1.1: Ratings, Quick Replies, Account Linking, and More](http://messengerblog.com/bots/messenger-platform-1-1-ratings-quick-replies-account-linking-and-more/)

**Comment by MironV** [comment]
I just tried out some of the 1.1 stuff. Image/video support works fine with existing code via attachments. Quick replies don't work but it's an easy change (see #306). The Sender Actions (typing, etc.) would need to be added as new APIs or parameters to existing APIs (maybe as part of a conversation) but nothing too difficult. The Persistent Menu is a configuration API so you could just call that separately if you wanted.

**Comment by ansarizafar** [comment]
@MironV did you try Account linking?

**Comment by MironV** [comment]
@ansarizafar I have not, but from looking at it, the code to initiate the link is just an attachment so it's supported by the current codebase. The callback that's received needs to be processed which would be a change in Facebook.js. Right now it expects the JSON to have message, so you'd need to modify this line of code to accept account_linking and then process:
`var facebook_message = {
                recipient: {},
                message: {}
            };`

I don't have the time right now to properly test this otherwise I'd make a pull request. Hope it helps!
