### ISSUE TITLE
facebook "No matching user found"

### ISSUE THREAD

**Issue by Areks** [howdyai/botkit#312]
Hello guys, i got this error when i sending message to chat on facebook. I think it's my fail not the botkit, i tried to google this, but i really can't understand where is problem.

```
debug: API ERROR { message: '(#100) No matching user found',
type: 'OAuthException',
code: 100,
fbtrace_id: 'AGn41P1D1C9' }
```

**Comment by Ayeps** [comment]
I'm facing the same problem

info: Got an unexpected message from Facebook:  { sender: { id: '####' },

**Comment by maxhartshorn** [comment]
It would be great if someone could take a look at this. I get the same error even using the facebook demo. Is botkit no longer supporting Facebook?

**Comment by krismuniz** [comment]
These are two different problems.

The first one (@Areks): You are either trying to send a message to a user that is not match your criteria (it could be a phone number if you are doing customer matching or a page-scoped user `fb_id`).

The second one (@Ayeps): Botkit is receiving a new type of events that it does not currently support. As of today (Jul 14, 2016), `botkit` does not support message read receipts or message echoes. That's why you got that output.

Hope this helps :)

**Comment by crosofg** [comment]
@krismuniz Which criteria do you mean? Can you please explain in detail. All of a sudden I am getting the same error as mentioned by @Areks .

**Comment by RustyDev** [comment]
I'm facing this too with the example fb app:

    debug: GOT A MESSAGE HOOK
    debug: RECEIVED MESSAGE
    debug: CUSTOM FIND CONVO 1415822938445957 1415822938445957
    debug: I HEARD [ 'hello', 'hi' ]
    debug: API ERROR { message: '(#100) No matching user found',
      type: 'OAuthException',
      code: 100,
      fbtrace_id: 'Cevxr7GLrSc' }

**Comment by agamrafaeli** [comment]
Read receipts and echoes were both merged in #403

**Comment by peterswimm** [comment]
Let us know if #403 fixes the above issues!

**Comment by agamrafaeli** [comment]
@peterswimm I followed @krismuniz explanation and it made sense. #403 indeed solves the problem described by @Ayeps.

The problem that @Areks is describing could indeed be cause by a wrongful input of a user id.

**Comment by peterswimm** [comment]
closing as resolved
