### ISSUE TITLE
Allow doing async stuff in the hears middleware handlers

### ISSUE THREAD

**Issue by IonicaBizau** [howdyai/botkit#324]
It looks like for the `hears` middleware functions we can have currently only the `patterns` and the `message`.

It would be great to have also an optional callback function (third argument) which will allow us to run async stuff in the function.

**Comment by benbrown** [comment]
This would be nice, but would require a substantial change in how hearing works.  Probably not possible at the moment!

**Comment by IonicaBizau** [comment]
Um... wasn't this marked as enchantment? It's not possible now, hence the issue.

Thanks!

**Comment by peterswimm** [comment]
Me marking it as an enhancement shouldn't be construed as an endorsement, just describing the nature of the request ;)

**Comment by IonicaBizau** [comment]
@peterswimm Of course. 

Somebody I helped out with this library needed to have some async operation, and we ended up by using the `deasync` module to make the async operation synchronous. For obvious reasons, that is not the best solution.

Maybe another idea would be to return a promise. Or maybe `async/await` can help.

The use cases exist. I would suggest not closing the issue, because later somebody will open a similar one. Maybe you can be open for contributions in this direction.

**Comment by peterswimm** [comment]
Absolutely! And if a user wants to weigh in on this issue or comment on a newly created one, they are totally free to. The problem with your solution, and the reason I think Ben closed the issue is that the proposed fix has implications on various uses of hears that currently work fine, so while there is a need to address async operations, it is something that will have to be carefully considered as to not create more problems than are solved.

Our main goal with the issues on the repo are to keep issues active until resolution, so if we don't plan on working on something in the near term, and there isn't an active effort to submit a PR to address, we want to close the issues until a point they become relevant again.
