### ISSUE TITLE
Running different bots on same server

### ISSUE THREAD

**Issue by SHBelsky** [howdyai/botkit#333]
I've been experimenting with different bots (namely Facebook and Twilio), and I was wondering if there was a way to host both a Facebook and Twilio bot in the same NodeJS project. When I currently try to do this, I can't create distinct web servers for both bots because they need to occupy the proper port, but they can't both occupy the same port.

I understand that you can use your own Express server instead of instantiating a new web server for each bot, but the documentation is unclear on how exactly to implement it. I've gone through both [the Facebook Messenger](https://github.com/mvaragnat/botkit-messenger-express-demo) and [Slack](https://github.com/mvaragnat/botkit-express-demo) examples, but I haven't been able to replicate it in the way that I would like. 

I'd ideally like to use one Express server for both Facebook and Twilio, then set up the proper routes (e.g. `https://mysite.com/facebook/receive` and `https://mysite.com/twilio/receive`) with it. With Facebook, [the routes don't seem so bad](https://github.com/mvaragnat/botkit-messenger-express-demo/blob/master/app/routes/routes.js), but I get confused [looking at the controller](https://github.com/mvaragnat/botkit-messenger-express-demo/blob/master/app/controllers/botkit.js). I'm confused on how much I need in order to have a single Express server (which, ideally, would also have a simple website or frontend aside from the bots) that also has the Botkit bots.

Thank you!

**Comment by bluetrane** [comment]
I'm interested in solving the same problem. Looking forward to a response.

**Comment by shirilad** [comment]
I'm running several facebook bots on the same server. I assume it could work the same way with some Twillo bots and some Facebook bots on the same server as well:

I've expanded the createWebhookEndpoint with another 'action' parameter, so that:
var action = action ? action : '/facebook/receive';
and then:
webserver.post(action, function(req, res) { ... (instead of the hard coded '/facebook/receive')

At this point, the example you were looking at can do the trick, only you don't really need the handler or routes now (I only have one or two extra pages aside my bots, so i just use app.get(..). If you have your own routes it's ok as well, but in any case in this approach you won't need the webhooks routes they have in the example).

In my server.js, I'm creating an express app, and then:
* creating all of the facebookbots
* initiallizing every controller.webserver to app
* start server
* setting up every bot by subscribing to fb events , createWebhooksEndpoints with a unique action for the specific bot (instead of '/facebook/receive')

(Btw, regarding the changes in createWebhooksEndpoints, I didn't ask for a pull request yet cause I though I might do some more tweaks as I go along, and also wanted to make sure it's ok before carrying on with it, but if it's of interest and the botkit guys don't mind, I can make a pull request as well...)

**Comment by SHBelsky** [comment]
I was able to do that with an Express `app`, and it's compatible with `createWebhookEndpoints` so that I can still use all the appropriate routes and not need to manually catch the route/action. If I'm understanding what you're doing with `action` correctly, `action` is a placeholder for the different routes for each individual bot you have, correct?

If I'm using my own Express server, do I still need to manually subscribe to Facebook events? This might be related to [a separate issue I'm having](https://github.com/howdyai/botkit/issues/337#issuecomment-234950544) when trying to get Facebook location data.

**Comment by shirilad** [comment]
Yeah, action is a place holder for each route (called it action cause i think of it more as a controller action, but you're right).
If you wanna upload a facebook and twillo bot than they already have separate routes, so it's not a problem actually...

AFAIK, if you're using your own express server you still need to manually subscribe to fb event, the same way that appears in the express-facebook example you've put in, and/or the same way that appears in botkit's Facebook.js setupWebserver method (I actually used their method as an example to what I should do than the demo you've attached, cause they're practically using an express server themselves, and we just wanna use the same webserver in several bots).

Saw your other issue as well. you're not subscribed to facebook events that would explain it, thought I'm not sure how you're evene getting any other message if that's the case :/

**Comment by rossthedevigner** [comment]
@SHBelsky @shirilad I just came across this project and that was my first thought; How do you manage multiple bots that can respond to the same endpoint from each service? Do you have a sample gist by chance? I don't see an example in the repo for this use case.

**Comment by shirilad** [comment]
@rossthedevigner  In my case the multiple bots respond to different endpoints, so I wouldn't know, sorry..

**Comment by rossthedevigner** [comment]
@shirilad Just out of curiosity, are you having to double the logic for the multiple endpoints or do they each behave and respond differently?

**Comment by shirilad** [comment]
@rossthedevigner  not entirely sure that I follow... 
These are literly several different bots, I just wanted then to run on the same server. In my case they are all Facebook bots, btw.
So the logic of each bot is different, but the message and its parsing act the same way and is done via the botkit infra.

**Comment by benbrown** [comment]
Botkit currently does not have good support for multiple Facebook bots inside a single controller.

That said, it IS possible to have multiple controllers of any platform inside a single app.
