### ISSUE TITLE
Asynchronous conv.stop happens before conv.next

### ISSUE THREAD

**Issue by rajhans** [howdyai/botkit#356]
In the following sample flow when doing
conv.say("foo")
conv.next()
conv.stop()

Due to asynchronous nature of the function calls, stop sometimes happens before next and say.

**Comment by yannderyckedotcom** [comment]
next try to find the next step and after stop. so you don t have to use stop() after

**Comment by EloyRedondo** [comment]
You can't use conv.stop() after a conv.say().
If you want to use conv.say() and then stop the conversation, you just need to use conv.next() to jump to the end of the conversation: conv.on('end', function(conv){}
The next jump will be the end of conversation because each conv.ask() must be into the callback function of the previous conv .ask(). For example:
´´´conv.ask('first question', function(){

});´´´
