### ISSUE TITLE
Multi-node service

### ISSUE THREAD

**Issue by karthik-mudiam** [howdyai/botkit#402]
From my understanding, when i have botkit running on multiple servers and i start a conversation with a user using botkit.startConversation() then the messages from that user should always go to the same server of botkit. Basically have stickiness based on userid.

For example:
User: Hi
Bot: Hi, what is your name?
User: TestBot
Bot: Hi TestBot, how can i help you?

In case of above conversation, if the first message from the user goes to server1 and the second message from the user goes to server2 then the conversation breaks. Is the understanding right?

**Comment by lucasgreene** [comment]
@karthik-mudiam If you have the teams you service split between the servers, then all the messages will go to the correct servers, as long as they dont go down. So you would have teams A,B,C serviced by server1 and D,E serviced by server2. Each server will only have an RTM connect (websocket) for the teams they service, so all the messages will go to the correct server (stickiness on steroids). This is how most people I know are doing scaling. You just have to manage which teams will be assigned to which servers (balancing), and what happens when a server goes down/team uninstalls the bot. 

If you put all teams on all servers, then without some sort of complicated websocket front server all  messages will go to all servers, and you will actually see 2 replies (duplicate) from the bot for every message you send. 

The way to think about it is the botkit process is the one creating the connection (unlike a typical server scenario where you just wait for the client to connect), so for each process you can control which connections are made.

**Comment by peterswimm** [comment]
closed as answered
