### ISSUE TITLE
Quick Replies are not supported by Botkit? [Facebook]

### ISSUE THREAD

**Issue by morsidi** [howdyai/botkit#417]
Has anyone managed to get it to work with convo.say/ask ?

**Comment by alaabatayneh** [comment]
@morsidi 
Are you using the latest version of Botkit? Quick replies should work.
Please paste the code you are using to send the quick replies.

**Comment by chriscomrie** [comment]
controller.hears(['raleigh'], 'message_received', function(bot,message){
  bot.reply(message, {
    "text": "What day would you like to go out?",
    "quick_replies": 
          [
            {
              "content_type": "text",
              "title": "Thursday",
              "payload": "thursday_test"
            },
            {
              "content_type": "text",
              "title": "Friday",
              "payload": "friday"
            },
            {
              "content_type": "text",
              "title": "Saturday",
              "payload": "saturday"
            }
          ]
        })
    })

**Comment by chriscomrie** [comment]
controller.on('facebook_postback', function(bot, message) {
    if (message.payload == "raleigh_test") {
            bot.reply(message, {
              "text": "What day would you like to go out?",
              "quick_replies": 
            [
              {
                "content_type": "text",
                "title": "Raleigh",
                "payload": "raleigh_test"
              },
              {
                "content_type": "text",
                "title": "Chapel Hill",
                "payload": "chapel_hill"
              },
              {
                "content_type": "text",
                "title": "Boone",
                "payload": "boone"
              }
            ]

        },
                function(response, convo) {
                // whoa, I got the postback payload as a response to my convo.ask!
                convo.next();
            }
        )}
    })

**Comment by bjoernklose** [comment]
The issue here seems to be that the current changes that came with [Messenger API 1.1](https://messengerblog.com/bots/messenger-platform-1-1-ratings-quick-replies-account-linking-and-more/) have not been fully implemented in botkit just yet.

Compare #306 for instance (QuickReplies) and #305 for the starting point.

This has been merged into master, but not made it into a release version (https://github.com/howdyai/botkit/releases).

Latest tagged release was v0.2.2 which came out in June (before Messenger API 1.1 on July 1st).

So my (hopefully temporary) solution is: Manually checkout current master branch instead of relying on a pinned version.

**Comment by benbrown** [comment]
0.4 includes these changes!
