### ISSUE TITLE
Interactive replies in conversations

### ISSUE THREAD

**Issue by rjbaker** [howdyai/botkit#425]
Hi there,

I'm trying to use an interactive reply from a button as part of a conversation. I've used the example code provided in [the botkit slack readme](https://github.com/howdyai/botkit/blob/master/readme-slack.md#using-interactive-messages-in-conversations)

In practice, my buttons appear. However after clicking a button, neither callback is ever handled. Instead, Slack just displays the following:
<img width="444" alt="screen shot 2016-09-26 at 12 02 45" src="https://cloud.githubusercontent.com/assets/783245/18832058/302b89d2-83e1-11e6-8a6b-5d05597a591a.png">

**Comment by lucasgreene** [comment]
@rjbaker Do you have a webhook set up? You need to set up a webhook to receive the interactive callback and set that path up in the slack app admin. 
https://api.slack.com/docs/message-buttons
https://github.com/howdyai/botkit/blob/master/readme-slack.md#message-buttons

I highly recommend localtunnel for local testing because you'll need SSL certs otherwise

**Comment by peterswimm** [comment]
Did the above solve your question? Closing for now, if you still need assistance please ask in:

http://dev4slack.xoxco.com/
