### ISSUE TITLE
Tunnel url not working for facebook webhooks

### ISSUE THREAD

**Issue by shivamsk** [howdyai/botkit#457]
As mentioned in the readme-facebook.md, I've run the command in the botkit folder cloned from github
page_token=xyzsdfdf verify_token=xyz_verify_token node facebook_bot.js [--lt [--ltsubdomain my_app_name]]
Logs:
info: *\* Starting webserver on port 3000
info: *\* Serving webhook endpoints for Messenger Platform at: http://MY_HOST:3000/facebook/receive

It's not giving the https url to be used in webhooks.

**Comment by RustyDev** [comment]
If you're copy/pasting, the end of the command needs to be altered depending if you want to use localtunnel:

```page_token=xyzsdfdf verify_token=xyz_verify_token node facebook_bot.js```

or

```page_token=xyzsdfdf verify_token=xyz_verify_token node facebook_bot.js --lt 8000```

also make sure to use the correct page token and verify token from facebook

**Comment by agamrafaeli** [comment]
Put in a PR to clarify correct usage of --lt

**Comment by peterswimm** [comment]
https://github.com/howdyai/botkit/pull/467 Linking for reference

**Comment by peterswimm** [comment]
pending a fix!

**Comment by agamrafaeli** [comment]
@peterswimm Any reason not to merge #467 ?

**Comment by peterswimm** [comment]
@agamrafaeli we should be reviewing some PRs for a new update in the next week or so, hopefully we can get feedback to you shortly!

**Comment by hakey1408** [comment]
i'm having the same issue as @shivamsk . I setup all the correct fields in the .env file (USE_FACEBOOK=true, watsonID, PSW, etc...).
I open the cmd and type 

> 'lt --s watsontyres --p 5000'

 where watsontyres is my appname, the reply is 

> 'your url is: https://watsontyres.localtunnel.me'.

I type 'node server.js' and:

> _info: ** No persistent storage method specified! Data may be lost when process shuts down.
> info: ** Serving webhook endpoints for Messenger Platform at: http://MY_HOST:undefined/facebook/receive
> Facebook bot is live
> Client server listening on port 5000_

So i think the problem is here, because it doesn't show the correct url.
Next i go on facebook dev page and when i try to setup the webhook it says 502 bad gateway.
Can you help me solving this problem please?
