### ISSUE TITLE
Can't ReplyPrivate to Channel message?

### ISSUE THREAD

**Issue by emorling** [howdyai/botkit#520]
I can't get a Slack Bot to reply in private to the person that posted a message in a channel. Shouldn't this be possible?

```
controller.hears('test', ['ambient'], function(bot,message) {
	// THIS DOES NOT WORK:
	bot.replyPrivate(message,'I hear you loud and clear.');
});
```

**Comment by jonchurch** [comment]
`bot.replyPrivate()` is used to respond to slash commands, and will not work elsewhere I believe. 

Do you intend to reply ephemerally, or just start a direct message thread with the user?

**Comment by tiagosiebler** [comment]
@jonchurch I'm quite keen on this too, would be nice for the bot to reply in-channel similar to the slackbot:
![screen shot 2017-07-06 at 11 59 23](https://user-images.githubusercontent.com/14090872/27908208-96794c98-6242-11e7-9046-1e99fbf69e7b.png)

I know that the reply in that screenshot is in the context of a slash command, but I'm thinking of user-specific info that could be provided here instead of a direct message or public post.
