### ISSUE TITLE
Send middleware - who is the bot talking to?

### ISSUE THREAD

**Issue by arnthorsnaer** [howdyai/botkit#551]
I'm adding a custom middleware to send (controller.middleware.send.use) which is working as far as getting information on what text is being send and what the channel is but I am unable to figure out the user being communicated with.

Can I figure this out using the channel in the message?

**Comment by benbrown** [comment]
@arnthorsnaer you can look at the message.user field. Is that not working?

**Comment by arnthorsnaer** [comment]
Given this middleware function

```
controller.middleware.send.use(function(bot, message, next) {
    console.info(message)
    next();
  });
```

When I use "bot.startPrivateConversation" to send a message to the user the message object contains `{text: "relevant text", channel: "D13E96..."}` 

Additionally when I use "bot.api.chat.postMessage" then the middleware function does not execute.

**Comment by arnthorsnaer** [comment]
Another strange thing I noticed - when using the bot.api.chat.postMessage the controller.middleware.receive.use middleware executes (strange since I thought it only executed when the bot receives a message.

Is it possible that the middleware functions only work with RTM?

**Comment by benbrown** [comment]
Hey @arnthorsnaer sorry I misread your original question.  There is not currently a way to reliably know who the message is addressed to, because for slack, the only required field is the channel.

This is an interesting point, and it may be that we _should_ ensure that a user field is present there since Botkit is always talking to a specific user, even if in a public channel. 

On your second point, I believe you are seeing the receive middleware fire in response to message delivery confirmations and/or echos from the events API.
