### ISSUE TITLE
Is there a non-Express way to add https to my Facebook bot?

### ISSUE THREAD

**Issue by bencooper222** [howdyai/botkit#596]
I'm done with local development and am trying to get production setup. However, I can't figure out how to make the webserver an https one. I saw [this](https://github.com/howdyai/botkit/issues/194) but it wasn't helpful. Do I have to create my own Express server for this to work or is there an easier way to do this?

**Comment by Dan-Wood** [comment]
I always use Nginx and it's reverse proxy option to forward traffic to the Express server, IMO just makes it easier to add certs with things like Lets Encrypt.

These might help you out though
https://github.com/Daplie/greenlock-express
https://community.apigee.com/articles/28041/nodejs-and-self-signed-ssl-certificates.html

**Comment by musicaljoeker** [comment]
I recently solved a similar problem. I used Nginx as a web server, installed a valid SSL certificate so that it can run on HTTPS. This isn't the hard part, just Google around for a guide on how to get and install a valid SSL certificate on Nginx.

The harder part is taking all port 443 and port 80 traffic and redirecting it to a new port. This new port is the one you'll start botkit on. <a href="https://www.ghostforbeginners.com/how-to-proxy-port-80-to-2368-for-ghost-with-nginx/">This article</a> was really helpful for me in showing how to forward all traffic from one port to another with Nginx. Good luck!

**Comment by pourmesomecode** [comment]
The easiest way I found @bencooper222 was to setup an AWS account. Setup an EC2 instance for Ubuntu.

Follow this guide on DigitalOcean - https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04

Once you've done that. You can load balance your ec2 instance, AWS gives you a checkbox to basically say, do you want to use an SSL certificate. You select yes, setup your server and there. You have a server using https and since you followed the digitalocean all you should the routes setup for proxying or at least, can understand enough of the tutorial that you can find and change what you need to get it setup.

**Comment by bencooper222** [comment]
Thanks all!
