### ISSUE TITLE
[Messenger] replyWithTyping behavior

### ISSUE THREAD

**Issue by stephentt-me** [howdyai/botkit#616]
My code:
```javascript
bot.replyWithTyping(message, "This is a very long long")
bot.replyWithTyping(message, "long and long")
bot.replyWithTyping(message, "text.")
```
Expect:

> - 1s typing indicator - This is a very long long
> - 1s typing indicator - long and long
> - 1s typing indicator - text.

Reality:

> - 1s typing indicator - This is a very long long
> - long and long
> - text.

All of the following messages popped out immediately, which is a very bad UX. Is this a bug or something by designed?

**Comment by peterswimm** [comment]
Check this out: https://github.com/howdyai/botkit/issues/507

Are you using Events or RTM api?

**Comment by jonchurch** [comment]
I think they are on Messenger, will try to test this soon.

**Comment by xJeremie** [comment]
Yup. This is on Messenger. And I don't think it can fix easily...  
```javascript
setTimeout(function() {
    bot.reply(src, resp, cb);
}, typingLength);
```  
Any idea on this?

**Comment by jonchurch** [comment]
What I think is happening here is all three timeouts are being set
simultaneously, for the same amount of time, and then executing the reply
at the same (or nearly the same) time.

Bot.reply in its various flavors does not use message queuing, so you could
hack around this by nesting bot.replyWithTyping in callbacks. (Yuck!)

You should use a conversation, which allows you to queue messages one after
another. However, I dont think there is currently a way to reply with
typing from a conversation? I will ask over on dev4slack.slack.com (the
slack community for botkit developers), otherwise this is a great feature
request!

**Comment by xJeremie** [comment]
@jonchurch Hey, I'm thinking the same about the need of a message queue. Seem it the easiest way to solve the problem.

But I have no idea how to implement it. What do you think?

**Comment by jonchurch** [comment]
I have not started on this, but Botkit has Conversations which allow for the queueing of messages. The messages are sent one per second on the controller's tick. 

You could alter conversations to add a method that sends a typing indicator, creates a delay, and then sends the message.

**Comment by devhaoy** [comment]
+1 @jonchurch it d be great to have a typing indicator convo method for Facebook (wish i had enough understanding of Botkit to do it myself). This would be a great ux enhancement for a conversation management framework. 
I m currently using bot reply with typing to get the indicator Activated and this is a nassive headache.

**Comment by Naktibalda** [comment]
I have the same issue with [SocketBot](https://github.com/howdyai/botkit/blob/dev/webchannel/lib/Sockets.js#L120-L142), but I was going to report it as "out of order responses caused by premature input" , because typing length calculation sets timeout based on text length, so a long reply to the first input appears later a short reply to the second input.

Expected conversation (it would work this way with typing disabled):
```
U: input1
B: long response
U: input2
B: short response
```
The actual result:
```
U: input1
U: input2
B: short response
B: long response
```

It would be an improvement if responses appeared in the right order:
```
U: input1
U: input2
B: long response
B: short response
```

Disabling typing speed is the easiest solution, but it causes "a wall of text" effect.
A better solution would be to implement a reply message queue.
In case of SocketBot, I could easily implement it in the client side because it only has to queue messages for one user.

Doing it in CoreBot (or copy-pasting to multiple "bots", like it happened with typing speed code),
would be a more universal solution.

I need advice on where to keep messages queues.
Would it be OK to add a new `replyQueues` property to `var botkit` in [Corebot](https://github.com/howdyai/botkit/blob/master/lib/CoreBot.js#L19)?
It would be an object having a value of `message.user` as a key and a queue (probably a simple array initially) as a value.
Also I would have to store an indicator if there is a scheduled event to send reply for a specific user - it could be stored in a separate object, e.g. `replyWorkers` or by adding another level to `replyQueues`:  `"ABCDEF": {"queue": [], "scheduled": false}`
A modification to reply/replyWithTyping methods would be that instead of using `setTimeout`, it would add a message to the right queue, and only call `setTimeout` if there isn't one set for the current user. Function executed after timeout would send and remove the oldest message from the queue and set another timeout for itself if the queue isn't empty.

Does that sound about right or is it completely insane/silly? Am I missing some good practice or a useful library?

**Comment by benbrown** [comment]
The solution to this problem is to use the conversation system.
If you are going to send more than one reply, conversations will keep them in the proper order.
Conversations ALREADY ARE the queue system that you describe.
