### ISSUE TITLE
team_slashcommand.js doesnt work with the latest build

### ISSUE THREAD

**Issue by ynot408** [howdyai/botkit#656]
1. clone the repo, npm install ...
2. cd examples
3. configure a slash command with public ip:port 
4. node team_slashcommand.js (make sure the port in this file and the configuration in slack is the same)

5. now send the slack command... The below message is seen-
Darn – that slash command didn't work (error message: `Timeout was reached`). Manage the command at ..

6. git checkout 7507ecd15d9f86334eb199c9ac315f6160658eb5
7. node team_slashcommand.js 
8. Now the command works and we see the reply in the window.

All commits after 7507ecd15d9f86334eb199c9ac315f6160658eb5, doesn't execute team_slashcommand.js

**Comment by GuilhermeMedeiros** [comment]
`0.4.10` times out and `0.4.9` works here.

**Comment by Ferrari** [comment]
any update?
Seem slash command cannot work under latest botkit.

**Comment by ifreecarve** [comment]
possibly the same issue.  Minimal example:
```javascript
// boilerplate suggested at https://api.slack.com/tutorials/easy-peasy-slash-commands
var Botkit = require('botkit');

var config = {
    debug: true,
};

var appConfig = {
    clientId: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    scopes: ['commands']
};

var botConfig = {
    token: process.env.SLACK_TOKEN
};

var controller = Botkit.slackbot(config).configureSlackApp(appConfig);
var bot = controller.spawn(botConfig);

controller.setupWebserver(process.env.PORT, function (err, webserver) {
    if (err) {
        console.error(err);
        process.exit(1);
    }

    webserver.use(function (req) {
        console.log("Incoming web request: " + JSON.stringify(req.body, null, 2));
    });
    controller.createWebhookEndpoints(webserver);
});

controller.on('slash_command', function (bot, message) {
    console.log("SUCCESS");
    bot.replyPublic(message, "SUCCESS");
});
```
The result of running this with `node minimal` results in the `Timeout was reached` error mentioned above.  This is strange in particular because (as shown here) botkit receives the incoming request from Slack.  I have no reason to believe that my app is misconfigured, because intentionally mangling the credentials results in no packet being sent to my webserver.

<img width="970" alt="screen shot 2017-06-20 at 7 48 32 pm" src="https://user-images.githubusercontent.com/583459/27361137-60c98942-55f3-11e7-87ec-45da07b67c4c.png">

**Comment by ifreecarve** [comment]
Some poking around seems to suggest that 
`webserver.post` on this line is (somehow) malfunctioning:
https://github.com/howdyai/botkit/blob/master/lib/SlackBot.js#L134

Putting a logging statement within that callback function doesn't produce output.

**Comment by jonchurch** [comment]
Checkout possible resolution in #823
