### ISSUE TITLE
Microsoft Bot - How to receive user id

### ISSUE THREAD

**Issue by abhi007tyagi** [howdyai/botkit#672]
I am running Microsoft bot and enabled it for Skype.
I want to know how I can receive user id at the bot's end?
My bot needs to identify to whom it is communicating. 

`controller.hears(['hello', 'hi'], 'message_received', function(bot, message) {
    console.log("MESSAGE-->"+message);
    console.log("MESSAGE USER-->"+message.user);
    controller.storage.users.get(message.user, function(err, user) {
        if (user && user.name) {
            bot.reply(message, 'Hello ' + user.name + '!!');
        } else {
            bot.reply(message, 'Hello.');
        }
    });
});`

Console does not print anything on terminal. and I only receive "Hello" as reply.
Where can I find the documentation for message object supported by Howdyai botkit?

**Comment by vdnt** [comment]
If you start bot with debug:true console  prints all those id's..

```
var controller = Botkit.botframeworkbot({
    debug: true
});
var bot = controller.spawn({
    appId: process.env.app_id,
    appPassword: process.env.app_password
});
```

**Comment by abhi007tyagi** [comment]
thanks, but I need the skype user id to whom bot is communicating like "john07" is chatting with bot, then I can capture the user id "john07" even if debug is false. I am exploring to use the user id for authentication purpose.

**Comment by jrjohnson** [comment]
No idea if it is the same but using slack the userId is available as `message.user`.

**Comment by jonchurch** [comment]
The message object passed to your bot will have a user field with an id,
but I dont know enough about bot builder or skype to know what that id
entails.

There should be some skype api call where you exchange the userid for skype
name.
On Fri, Mar 10, 2017 at 3:30 AM Jonathan Johnson <notifications@github.com>
wrote:

No idea if it is the same but using slack the userId is available as
message.user.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/howdyai/botkit/issues/672#issuecomment-285608538>, or mute
the thread
