### ISSUE TITLE
Support outgoing message queueing (so that the bot won’t break the message sending rate limit)

### ISSUE THREAD

**Issue by RafaelCosman** [howdyai/botkit#69]
Proposed by @benbrown.

**Comment by stanislavfeldman** [comment]
This will be very useful, because if you break the limit your bot will be disconnected.

**Comment by Rubenkl** [comment]
Yes! Maybe the option to override it manually? (for other services)

**Comment by PanMan** [comment]
Anybody worked on this, yet? Slack 'only' allows about 1 message/second.

**Comment by PanMan** [comment]
For now I have solved this in my code like this:
````
var timeQueue = async.queue(function(task, callback) {
    task.func();
    setTimeout(callback, task.timeOut);
}, 1);
````
And to send something:
````
 timeQueue.push({timeOut: 1100, func: function(){
  bot.startPrivateConversation({user: member.id}, function(err, convo){
    if (err){
      console.log('ERR:',err);
    }
    convo.say('Sorry, PanMan needs to test something. You can disgard this, and send PanMan funny gifs as a reply')
  });
}}, function(err) {
          // console.log('finished processing item');
        });
````

HTH

**Comment by MiroValchev** [comment]
This is so @&#$ up! Tried a lot of workarounds and nothing works.
I have over 2000 teams and can't connect to them.

Botkit is obfuscating the 429 response instead of properly propagating it.
"If you go over these limits when using our HTTP based APIs, including Incoming Webhooks, Slack will start returning a HTTP 429 Too Many Requests error, a JSON object containing the number of calls you have been making, and a Retry-After header containing the number of seconds until you can retry."

For that reason, I can't properly handle when the limit is reached.

`bot.startRTM(function (err, bot) {`
err is not thrown here for 429

@RafaelCosman is there anyway this is finally fixed?! 
Either fix this internally or make it easy to detect the problem on bot.startRTM.
For bots with lots of teams this is a huge problem.

**Comment by tnilles** [comment]
I think that's quite a big issue, any news on this? I'd be happy to help if I can.

**Comment by benbrown** [comment]
@tnilles We'd love input. It is an important issue.

However, building a reliable outgoing queue to handle this is not something that would normally belong in a library like Botkit. What do you suggest?

**Comment by tnilles** [comment]
Well, I think this could be confusing to newcomers to botkit/slackapi. The first thing to do would be to mention the issue in the docs, and if you don't intend to add a queue mechanism maybe point the reader to a workaround (like @PanMan did).

Excuse me for asking, but why wouldn't a queue be included into botkit? This seems to be something every botkit user would want (ie. not breaking the bot because of the api limits). I might be wrong, and there's probably a good reason to not do that - but I'm not sure why.
