### ISSUE TITLE
Interactive Message Callbacks within Conversations Do Not Work [Slack]

### ISSUE THREAD

**Issue by lightyrs** [howdyai/botkit#704]
In the Slack Readme, you provide an example:

https://github.com/howdyai/botkit/blob/master/readme-slack.md#using-interactive-messages-in-conversations

While I'm able to successfully have conversations and also able to do normal interactive messages with callbacks, the combination of the two does not work as advertised in this section of the readme.

It seems that when the `interactive_message_callback` is triggered, we lose any `convo` context.

Please advise.

**Comment by jonchurch** [comment]
Are you referring to not having convo context within the `'interactive_message_callback'` event listener? Or within the conversation handling the button's value?

Two events are fired if you have `interactive_replies: true` set, first for `interactive_message_callback` which is fired with the payload object received from slack, and a `message_received` that contains the value of the button as the text field of a message. 

When using the latter to respond to a `convo.ask()` with interactive buttons, the button's value is routed into your conversation handlers as a message and contains the whole convo object.

**Comment by lightyrs** [comment]
@jonchurch When I use the following handler:

```js
controller.on('message_received', function(bot, message) {
  jsome(message);
});
```

I see the events coming in, however, messages are coming in as:

```
{
  type: "desktop_notification",
  title: "****",
  subtitle: "#channel",
  msg: "1489546033.243008",
  content: "person: test message",
  channel: "C3XNJEF7G",
  launchUri: "slack://channel?id=C3XNJEF7G&message=1489546033243008&team=T0PNTDD7E",
  avatarImage: "https://avatars.slack-edge.com/2017-01-30/134368081907_99a3295406a75d62a623_192.png",
  ssbFilename: "knock_brush.mp3",
  imageUri: null,
  is_shared: false,
  event_ts: "1489546033.522579"
}
```

This event never gets picked up if I use `controller.hears` with `message_received`.  It would appear there is a configuration issue on my end.  Can you provide any guidance?

Thank you for your help.

**Comment by lightyrs** [comment]
This seems potentially related to https://github.com/howdyai/botkit/issues/663

**Comment by jonchurch** [comment]
I have never seen desktop_notification! Nor do I think you should be
either. :joy:

Using message_received is not a recommended way to listen to events. Its
just a firehose of message types Slack sends.

If you are using interactive messages in conversations, botkit will
automatically route the users input to the conversation for you.

You can use the interactive_message_callback event to do any sort of
updating the interactive message to make it interactive. Like changing the
state of a button once its been clicked, or updating the parent message
once an action has been completed.

Its easiest to route a button's payload into the conversation as if it were
a message from a user, to drive the conversation with clicks instead of
typed words. So unless you want to actually update your message again, the
interactive_message_callback can be ignored.

Here's an [example](
https://github.com/howdyai/botkit-starter-slack/blob/master/skills/interactve_messages.js)
of handling updating interactive messages from the botkit slack starter
example. You can add the bot to a team from [here](
http://botkit-slack.glitch.me/) and say 'tasks' to the bot to test it out.

**Comment by lightyrs** [comment]
Thanks.  I suppose the bug I'm reporting is that this behavior (below) — is not functioning, although I'm able to successfully utilize all other documented functionality of botkit.

```
If you are using interactive messages in conversations, botkit will
automatically route the users input to the conversation for you.
```

**Comment by lightyrs** [comment]
@jonchurch In this comment, the user also experiences the `desktop_notification` issue.  I think this is a legitimate issue.

https://github.com/howdyai/botkit/issues/663#issuecomment-280455787
