### ISSUE TITLE
Bot is failing to run

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#725]
I don't understand the step number 5;

>   Run the example bot app, using the two tokens you just created. If you are not running your bot at a public, SSL-enabled internet address, use the --lt option and note the URL it gives you.
> 
> `page_token=<MY PAGE TOKEN> verify_token=<MY_VERIFY_TOKEN> node facebook_bot.js [--lt [--ltsubdomain CUSTOM_SUBDOMAIN]]`

 I've created the app in facebook and I have my page token and verify_token. After that I went in the file app to set them:

 "page_token": {
          "description": "page_token"
      },
      "verify_token": {
          "description": "verify_token"
      },
      "studio_token": {
          "description": "Token associated with your bot in Botkit Studio",
          "required": false
      }

  I am using ngrok instead of localtunel, so what I did is,after setting my webhook with the uri gotten for ngrok,  I opened my command prompt and typed:

`page_token=page_token verify_token=verify_token node facebook_bot.js`

And I got the error : 
![snap](https://cloud.githubusercontent.com/assets/13017395/24175433/41f692b4-0ea7-11e7-8bb2-d11e0077ec2e.PNG)

And if I run : 
node bot.js
I get : 
![snap2](https://cloud.githubusercontent.com/assets/13017395/24175491/7a27f45c-0ea7-11e7-8c79-7f870c051c93.PNG)

I don't know really how to run this step 5 and I don't understand what it does even.

**Comment by jonchurch** [comment]
The app.json file is for heroku, disregard it if not deploying to heroku. 

The steps you are following are for a different example, called facebook_bot.js. It looks like you are using the fb starter kit. The setup instructions for that are [here](https://github.com/howdyai/botkit-starter-facebook/blob/master/readme.md#get-started)

Run`page_token=<YOUR PAGE TOKEN> verify_token=<VERIFY TOKEN> node bot.js` and you should be good to go!

To understand

**Comment by MagSag** [comment]
I tried to do that but it giving me error saying : 

![page_token](https://cloud.githubusercontent.com/assets/13017395/24185405/1787e19e-0ee4-11e7-937f-5797623ee2cf.PNG)

I am running the command from the project folder as you can see in the image.

**Comment by jonchurch** [comment]
Please show me the full command you are entering to get that last error.

**Comment by MagSag** [comment]
@jonchurch This is the command: 

> D:\botproject\botkit-starter-facebook>page_token=rysfldl68u848484jjf verify_token=fdsury687487848 node bot.js

Which gives the error saying 

> 'page_token is not recognized as an internal or external command,operable program or batch file.

**Comment by jonchurch** [comment]
It looks like youre running windows, is that correct?

Im not familiar with setting environment variables from the commandline for
windows. Id suggest looking up how to do this for your version of windows
to proceed.

That, or maybe look into the dot-env npm package, which should load
environment variables for you from a .env file

**Comment by MagSag** [comment]
Yes I am on windows. What do you mean by environment variables? So these page_token and verify_token are environment variables?
The problem is, I even don't understand what the command mean a part from it has to run my application. May be if I understand it I may solve the problem.

speaking of 

> maybe look into the dot-env npm package, which should load environment variables for you from a .env file

I am new to node.js

**Comment by MagSag** [comment]
>  So these page_token and verify_token are environment variables? I got it now they are, but it seems there is a problem using them in windows so I should go for what you are proposing me 

> maybe look into the dot-env npm package, which should load environment variables for you from a .env file
Thanks a lot for your guidance.

**Comment by jacobwilliamroy** [comment]
The quick fix is to:

1.
Create two environment variables `page_token` and `verify_token` and set their values to the appropriate access tokens. On the windows command line (CLI) this is done by typing:
`set page_token=<YOUR PAGE TOKEN>`
`set verify_token=<YOUR VERIFY TOKEN>`

2.
Then, restart your CLI if it was already running. 

3.
Then simply type `node bot.js` without the `page_token=<blah> verify_token=<bluh>`  part and everything will be fine, so long as you remember to repeat steps 1 and 2 every time your tokens expire.

If you would like an explanation of why this works, read on.

I opened up the bot.js file and did a `ctrl-f` search for `page_token` and `verify_token`. And found these references:
`if (!**process.env.page_token**) {`
`   ...`
`}`

`if (!**process.env.verify_token**) {`
`    ...`
`}`
`page_token` and `verify_token` are properties of `process.env` which is a property of `process`: a global object specific to node.js. To quote from the documentation at https://nodejs.org/api/process.html#process_process_env:

> The process.env property returns an object containing the user environment.

Lo and behold if you write `console.log(process.env)` to a javscript file and then run it through node, it'll print out a list of all your environment variables. `console.log(process.env.username)` will print out the value of the `USERNAME` environment variable (in windows, environment variables are case-insensitive) and `console.log(process.env.foo)` prints `undefined`.

In the case of our bot.js file, the first few lines of code check to make sure `process.env.page_token` and `process.env.verify_token` exist, and if they don't, the program tells you to set them in your environment.

There are many ways to do this. You can search for 'environment variables' in the control panel GUI or use `set ` or `setx` (read windows docs if you want to know how these two commands are different).

Since facebook access tokens are temporary, step 5 in the documentation has you set the `page_token` and `verify_token` environment variables at compile time, but on a windows machine, the command line interface has to be restarted before you can access new or updated environment variables.

**Comment by jacobwilliamroy** [comment]
The command you're trying to enter is actually 3 commands chained together: 2 variable declarations and 1 program execution. The windows equivalent would be:
`set page_token=<YOUR PAGE TOKEN> & set verify_token=<YOUR VERIFY TOKEN> & node bot.js`

If your variable value contains spaces you'll need to use double quotes like so:
`set "[variable=[value]]"`

The `set` command is used to create and update environment variables. The `&` symbol is used to chain commands together.

NOTE: I had a previous answer here, but it had a lot of inaccurate information and an inelegant solution, so I deleted it.

**Comment by peterswimm** [comment]
@MagSag did you get this sorted?
