### ISSUE TITLE
Connecting same user with different accounts ex. Facebook and Slack

### ISSUE THREAD

**Issue by zolekm** [howdyai/botkit#726]
Hi,

can anyone help me how should connection between account be done. 

For example user create new bot user on slack and then same user start conversation from facebook is there and recommendation to link accounts between them?

I'm using mongo for storage and have different documents for facebook users and slack users & teams, also i'm using hapijs for web server

Best, Matija

**Comment by jkol36** [comment]
You could require the user to supply their email when they create a new bot user on slack and vice versa with facebook. You could then either generate some userId and associate the user id with the unique email then when they post on slack or facebook you can track them by the user id, and thus their email, or you could just use the email as the symbolic link. Anyway, unless i'm missing something that should solve your problem. if they end up using slack and facebook you can link them to that one email instead of having two seperate accounts for each.

**Comment by zolekm** [comment]
@jkol36 tnx for solutions i made decision to connect all users to one universal account
