### ISSUE TITLE
How do I send notification (like: messages, offers and packs etc) to Facebook messenger ?

### ISSUE THREAD

**Issue by deepakmhr** [howdyai/botkit#851]
I have user id's to which I want to send [notifications](https://developers.facebook.com/docs/messenger-platform/send-api-reference#request).
Are there any ways integrated with botkit framework ?

**Comment by jonchurch** [comment]
`bot.say(msg_obj)` is what you are looking for. Proactively sending a message to a user via their PSID. 

[Here's the docs](https://github.com/howdyai/botkit/tree/master/docs#botsay)

**Comment by yestouscool** [comment]
Hello I want to also send the message but the docs is not accessible anymore using botkit 0.7.0.  I have tried the following way in bot.js :  
`bot.say({text:`Hello, you  have a new person looking for you`,channel:data.sharerid});`

When I saw the above is not sending to the user I want to notify, I tried : 
```
let botsharer = controller.spawn({});
 botsharer.say({text:`Hello, you  have a new person looking for you`,channel:data.sharerid});
```

But still it is not sending to the user any message. I don't wanna use bot.reply because the person I want to notify is different from the person the chatbot is talking to currently.
