### ISSUE TITLE
Conversation with entire channel [help wanted]

### ISSUE THREAD

**Issue by berry-gsl** [howdyai/botkit#874]
Hi,

I'm trying to make the bot have a conversation with the entire channel.

I looked it up in the documentation but it seems you can only have conversations with the person that initiates it.

> startConversation() is a function that creates conversation in response to an incoming message. The conversation will occur in the same channel in which the incoming message was received. Only the user who sent the original incoming message will be able to respond to messages in the conversation.

So how can I start a conversation (or something equivalent) that all users are allowed to respond to?

If it helps: I'm trying to make a quizbot. So any person should be able to start/stop the bot and anyone should be able to try to answer the questions

**Comment by benbrown** [comment]
@berry-gsl this is not currently supported without some clever mis-application of middleware.

The key issue is that conversations are defined in the Slack connector by a user/channel combination.

It would theoretically be possible to sidestep this by using a middleware, perhaps the `receive` or `heard` endpoint, to change the message.user field so that it will match for any user.  This may have some weird consequences, but...something like:

```
controller.middleware.receive.use(function(bot, message, next) {

// keep original user id in case you need it
message.user_id = message.user;

// change the user field's value to be the same as the channel
message.user = message.channel;

next()
});
```
