### ISSUE TITLE
convo.ask() and convo.say() are not inserted in queue from callback of convo.addQuestion()

### ISSUE THREAD

**Issue by KarlisJ** [howdyai/botkit#884]
Either `convo.say()` and `convo.ask()` that are added in callbacks of `convo.addQuestion()` are not inserted into the queue but simply added at the end of queue. Consider this exaple:
```
controller.hears(['color'], 'message_received', function(bot, message) {
	bot.startConversation(message, function(err, convo) {
		convo.say('This is an example of using convo.ask with a single callback.');
		
		convo.ask('What is your favorite color?', function(response, convo) {
			convo.setVar('color',response.text);
			convo.say('Cool, I like ' + response.text + ' too!');
			convo.next();
		});
		convo.ask('Why  do you like {{vars.color}} color?', function(response, convo){
			convo.next();
		});
		convo.say('Ok bye');
	});
});
```
The order in conversation is:

> bot:What is your favorite color?
> me: Green
> bot: Why do you like green color?
> bot: ok bye
> bot: Cool, I like Green too!

**Comment by KarlisJ** [comment]
@jonchurch @pascalwhoop could you please try this code and send me full debug from console? Still having the issues with convo.ask() and convo.say() not added correctly to queue. I would really appreciate if I could get to see how it should be. Then I could compare with my logs.
```
bot.startConversation(message, function(err, convo) {
	convo.say('This is an example of using convo.ask with a single callback.');
	
	convo.ask('What is your favorite color?', function(response, convo) {
		convo.setVar('color',response.text);
		convo.say('Cool, I like ' + response.text + ' too!');
		convo.next();
	});
	convo.ask('Why  do you like {{vars.color}} color?', function(response, convo){
		convo.next();
	});
	convo.say('Ok bye');
});
```
This is driving me nuts. Does no else has ever encoutered this problem?

**Comment by benbrown** [comment]
Ah, this is confusing, but is the expected behavior.

When you call convo.ask or convo.say, you are enqueuing a message to be sent, in the order that the functions are called.

So your queue looks like:

This is an example...
What is your favorite color?
Why do you like color?
OK bye
Cool, I like color too!

There are a few possible solutions:

One is to use `convo.sayFirst()`, which pushes a message to the front of the queue instead of the end.

The other, more scalable solution, is to use the `threads` system to set up these messages ahead of time instead of dynamically.
