### ISSUE TITLE
How can I get the my bot user's timezone?

### ISSUE THREAD

**Issue by MagSag** [howdyai/botkit#968]
I really need to know  how I can get a true timezone of the my bot user. 

I will be having what I need in case the timestamp provided by facebook in message body is also calculate with the influence of the bot user timezone, but the problem is I don't know based on what facebook calculate the timestamp(do they include the user's timezone in calculation).

**Comment by Dreamiko** [comment]
Use JavaScripts built in Date class.

var date = new Date();

You can get the local time and timezone.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset

Hope this helps

**Comment by MagSag** [comment]
THanks, but this is not a browser thing, it is from the bot, what I want is to get either the timezone of the user who is send message to my bot, either the datetime(in his/her local timezone) of when he/she sent the message to my bot.

**Comment by hipitihop** [comment]
@MagSag I know for Slack, if your bot has permissions it can retrieve a list of user profiles via api.users.list  This will give you all profile properties, first name, last name, slack id etc. One of the properties is `tz` which if the user has set their timezone will be something like "Australia/Brisbane"

**Comment by MagSag** [comment]
For what I am doing user input can't be trusted, I need to get it automatically.

**Comment by ouadie-lahdioui** [comment]
You can get what you're looking for by calling ````message.timestamp````

````
controller.hears('hello', 'message_received', function(bot, message) {
    bot.reply(message, message.timestamp);
});
````

**Comment by MagSag** [comment]
The problem is, I don't know if that timestamp is calculated based on which timezone: client or facebook server. when it is 31/08/2017 10:00:00 in KINSHASA, it is 31/08/2017 12:00:00 in Kampala, The timestamp shouldn't be the same for people who are in Kinshasa and Kampala send the message at the same moment.

**Comment by ouadie-lahdioui** [comment]
I juste make some tests and i noticed that the timestamp sent by Facebook is all time in GMT time zone. So, based in your example the timestamp will be the same.

What you try to do exactly ?

**Comment by MagSag** [comment]
I need to be checking the time the user sent a message to my bot, and if his sending time(in timestamp)  is after the predefined time(in timestamp) I have set then reply to him with a specific message. So I have to consider the fact that 31/08/2017 10:00:00 in KINSHASA must not be the same timestamp as 31/08/2017 12:00:00 in Kampala; so that I don't send message to a user who is not supposed to receive it.

**Comment by jonchurch** [comment]
Are you using slack? Fb has tz data available in the Messenger profile api
call, btw

**Comment by MagSag** [comment]
FB, let me find out if it is  a tz set by user or detected by fb automatically, In my case nothing from user must be trusted.

**Comment by ouadie-lahdioui** [comment]
Nice catch @jonchurch 

@MagSag If I have understood correctly what you try to do :

1. Facebook send you a GMT timestamp per message (for example: 31/08/2017 08:00:00 GMT)
2. with fb user Profile API, you can get your user time zone so you can exactly know when they sent the message in their local tz (for example: if the tz returned by user profile api is +2 i'm totally sure that my user local time was 31/08/2017 10:00:00 GMT+2)
3. make some business logic based your predefined time 
4. beem, reply to user

Right ?

**Comment by julianusti** [comment]
@MagSag Ask the user, there's no other possibilities to get it, since facebook gives you a `timestamp` field, which is a [person's current timezone offset from `UTC`](https://developers.facebook.com/docs/graph-api/reference/user)

In fact `Timestamp != Time Zone`. 
A time zone can not be represented solely by an offset from UTC. Many time zones have more than one offset due to daylight saving time (aka "summer time") rules.

It is worth to mentioned that as per [this answer](https://stackoverflow.com/questions/19489257/parse-timezone-int-to-string-timezone-name-facebook-api) user's `timestamp` is not a static value and can be changed when the user logs in from different time zones, so the `new offset` will be set.

An `offset` is just a number that represents how far a particular date/time value is ahead or behind UTC.
- Most offsets are expressed in whole hours.
- But there are many that are 30-minute offset.
- And there are a few that are 45-minute offset.

A `time zone` contains much more:
- A name or ID that can be used to identify the zone.
- One or more offsets from UTC
- The specific dates and times that the zone transitions between offsets.
- Sometimes, a separate language-specific display name that can be presented to a user.

One can determine the correct `offset`, given a time zone and a datetime. But one **cannot determine the correct time zone given just an offset.**

Indeed, there is a **solution** but it's not accurate (**I would strongly recommend to ask user, so she/he is not frustrated afterwords**). 

By using [moment.js](https://momentjs.com/timezone/), we can implement smth. like the function below:
 
```
/**
 * IMPORTANT: An `offset` is just a number that represents how far a particular date/time value is 
 * ahead or behind UTC.
 * - Most offsets are expressed in whole hours.
 * - But there are many that are 30-minute offset.
 * - And there are a few that are 45-minute offset.
 *  It will not handles those 30-45 minutes offsets.
**/
const timestampToTimeZone = timestamp => {
   const signedTimestamp = timestamp > 0 ? `+${timestamp}` : `${timestamp}`
   return moment.tz.names().find(tzName => tzName.includes(`${signedTimestamp}`));
}

timestampToTimeZone(-2)  // "Etc/GMT-2"
timestampToTimeZone(2)   // "Etc/GMT+2"
timestampToTimeZone(7)   // "Etc/GMT+7"
timestampToTimeZone(-7)  // "Etc/GMT+7"

timestampToTimeZone(5.5) // undefined 
timestampToTimeZone(3.5) // undefined 
```
